In [1]:
import numpy as np

#### **NumPy** brings the computational power of languages like C and Fortran to Python, a language much easier to learn and use. With this power comes simplicity: a solution in NumPy is often clear and elegant.
#### Official documentation is at <a href = "https://numpy.org/doc/stable/"> Numpy Documentation. </a>
**NumPy’s** main object is the homogeneous multidimensional array**(ndarray)**. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.</p>

In [2]:
#Python List is heterogenous in nature. 
# numpy array is homogeneous in nature
lst = [1,2,3,'sree', 3.8]
np.array(lst)

array(['1', '2', '3', 'sree', '3.8'], dtype='<U21')

#### We can notice, all the elements of the python lists are converted to string elements(coercion)

In [3]:
type(np.array(lst))

numpy.ndarray

### Making arrays various ways

#### Making an array with python list

In [4]:
# Python list to numpy array
lst = [1,3,4,5,8,9, 10]
arr = np.array(lst)
arr

array([ 1,  3,  4,  5,  8,  9, 10])

In [5]:
#Shape of array
arr.shape

(7,)

In [6]:
lst = [[1,2,4], [6,7,8]]
arr = np.array(lst)
arr

array([[1, 2, 4],
       [6, 7, 8]])

In [7]:
arr.shape # 2 rows and 3 columns

(2, 3)

In [8]:
arr.ndim # Dimensions of the array - here it is 2

2

In [9]:
arr.size # How many elements -- size of the array

6

In [10]:
arr.dtype # array elements data type 

dtype('int64')

#### Making numPy array with arrange

In [11]:
mat = np.arange(1,101) # 1 to 101 means 1 to 100 but not 101 - last element is not inclusive
mat

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [12]:
# Reshaping the array - changing the dimensions 
# change the mat array to 10 by 10 array
mat = mat.reshape(10,10)
mat

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

#### Making an array from tuples

In [13]:
a = (1,2,3,5); b = (6, 8, 9, 10)
arr = np.array([a,b])
arr

array([[ 1,  2,  3,  5],
       [ 6,  8,  9, 10]])

In [14]:
# array with a specific data type
arr = np.array([1,2.3,3,5], dtype = 'float')
arr

array([1. , 2.3, 3. , 5. ])

In [15]:
arr = np.array(range(0, 10), dtype = 'int16')
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

#### Arrays from random numbers

In [16]:
mat = np.random.randint(100, 500, (10,10)) # random integers from 100 to 500 with 10, 10 
mat

array([[259, 200, 292, 341, 376, 117, 307, 442, 131, 221],
       [104, 139, 395, 359, 199, 176, 373, 497, 301, 172],
       [468, 217, 348, 435, 408, 416, 462, 386, 376, 477],
       [347, 267, 150, 274, 322, 272, 112, 121, 164, 220],
       [433, 190, 243, 202, 409, 367, 170, 243, 109, 115],
       [273, 118, 258, 390, 441, 226, 100, 140, 308, 137],
       [286, 326, 418, 304, 383, 209, 223, 300, 111, 105],
       [282, 228, 305, 235, 338, 354, 487, 407, 417, 494],
       [465, 178, 421, 122, 491, 211, 165, 450, 233, 452],
       [302, 427, 137, 277, 413, 470, 238, 299, 225, 434]])

In [17]:
type(arr[0])

numpy.int16

### Some Builtin functions of arrays

In [18]:
arr = np.array(range(10,100, 10), dtype = 'int16')
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=int16)

In [19]:
arr.mean()

50.0

In [20]:
arr.max()

90

In [21]:
arr.min()

10

In [22]:
arr.size

9

In [23]:
len(arr)

9

In [24]:
#cumulative sum array
arr.cumsum()

array([ 10,  30,  60, 100, 150, 210, 280, 360, 450])

In [25]:
#sorting in place
arr = [1,3,7, 0, - 1, 8]
arr.sort()
arr

[-1, 0, 1, 3, 7, 8]

In [26]:
arr = np.array([25, 9, 16, 64], dtype ="int16")
arr_sqrt = np.sqrt(arr)
arr_sqrt

array([5., 3., 4., 8.], dtype=float32)

#### Zeros array

In [27]:
zer_arr = np.zeros(shape = (3,5), dtype ="int16")
zer_arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int16)

#### Ones array

In [28]:
one_arr = np.ones(shape = (5,3), dtype = 'float')
one_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Diagonal of array

In [29]:
arr = np.arange(0,25)
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
np.diagonal(arr, offset=0, axis1=0, axis2=1) # Offset 0 gives corner to corner 

array([ 0,  6, 12, 18, 24])

In [31]:
np.diagonal(arr, offset=1, axis1=0, axis2=1) # offset 1 gives starting from 1 (1st rows second element)

array([ 1,  7, 13, 19])

In [32]:
np.diagonal(arr, offset=0, axis1=1, axis2=0)

array([ 0,  6, 12, 18, 24])

In [33]:
# Getting opposite diagonal

np.diag(np.fliplr(arr))

array([ 4,  8, 12, 16, 20])

#### Masking/Filtering the arrays

In [34]:
mat = np.arange(0,100)
mat = mat.reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
# get all the elements that are above 30 and less than seventy
filt = (mat>30)&(mat<70)
mat[filt] # returns a flat one dimension array

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
       65, 66, 67, 68, 69])

### Slicing/Indexing the mat

In [36]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [37]:
# selecting a single column 4th column 
# syntax array[ rowstart:rowend,columnstart : columnend]
mat[ 0:,3] # All rows but only 4th column ( 4th column index is 3)

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [38]:
# Selecting a single row 5th row
mat[5,0:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [39]:
# Selectning a chunk of rows
mat[0:3, ]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [40]:
#selecting a chunk of columns
mat[ 0:,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [40, 41, 42],
       [50, 51, 52],
       [60, 61, 62],
       [70, 71, 72],
       [80, 81, 82],
       [90, 91, 92]])

In [41]:
# Selecting a chunk 
mat[7:,5:7]

array([[75, 76],
       [85, 86],
       [95, 96]])