# Numpy Fundamentals 

### Numpy arrays come in two flavours
* 1 D Array
* 2 D Arrays ( Matrices )
Note :  A Matrix can be a single column or single row 

[NumPy Official reference site](https://docs.scipy.org/doc/numpy-1.15.0/reference/index.html) 



## How numpy library is useful in data science applications. Few points
- If dummy data needs to be created for testing some hypothesis, we can use numypy arrany created
- large data manipulations are possible. Example a numerical column each element needs to be multiplied by another column element. 


In [3]:
## Numpy standard library 
import numpy as np

### Creating NumPy Arrays Various ways

### 1. List to Arrays - 1 D Array

In [4]:
# From single list to Np Array
lst = [1,2,3,4]
arr = np.array(lst)

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
type(arr)

numpy.ndarray

In [7]:
# Shape of array
arr.shape

(4,)

In [9]:
#shape of array another way
np.shape(arr)

(4,)

In [14]:
lst1 = [1,2,'sree', 9] # Dissimilar elements in a list

In [15]:
np.array(lst1)

array(['1', '2', 'sree', '9'], dtype='<U11')

### 2. List of lists to Array - 2D Array

In [16]:
# From lists of lists
lsts = [[1,2,3],[4,5,6],[7,8,9], [10,12,13]]
arrs = np.array(lsts)
arrs

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 12, 13]])

In [17]:
type(arrs)

numpy.ndarray

In [18]:
# shape of arrs
np.shape(arrs) # 4 Rows  X 3 Cols

(4, 3)

In [19]:
arrs.ndim

2

### np.arange()

In [20]:
# np.arrange(start, end, step)
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

### np.ones()

In [22]:
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
np.ones((3,4)) # Tuple with rows, columns

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### np.zeros()

In [24]:
np.zeros(4)

array([0., 0., 0., 0.])

In [25]:
np.zeros((2,4)) # Tuple with rows, columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### np.eye()

In [26]:
np.eye(4) # diagonal ones of 4 by 4 matrix identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
type(np.eye(4))

numpy.ndarray

### np.linspace()

In [28]:
# np.linspace(start, end, step)
np.linspace(2,10, 5) # Equally spaced array 

array([ 2.,  4.,  6.,  8., 10.])

### np.random.randint() - Random distribution types

In [29]:
# np.random.randint(start, end , howmany)
np.random.randint(0,50, 10)

array([ 1, 34, 13, 45, 46, 46, 44,  6, 44, 24])

In [30]:
np.random.randint(0,50, (3, 5)) # 0 to 50 any random number, with 3 rows and 5 columns

array([[20, 17, 49,  4, 16],
       [17, 42, 34, 22,  3],
       [ 2, 42, 30, 41, 21]])

In [31]:
a = np.random.normal(0,50, 10)

### Conditional Selection / Filtering of Arrays

In [32]:
# create an array 
arr = np.arange(1,10)

In [33]:
# Create a boolean array of logical true or false based on the condition
# for example, get all the elements that are above 5
above5 = arr>5
above5

array([False, False, False, False, False,  True,  True,  True,  True])

In [34]:
arr[above5] # Get the above5 values out 

array([6, 7, 8, 9])

In [35]:
# Instead of two steps we can write this directly as below
arr[arr>5]

array([6, 7, 8, 9])

## Arrays Indexing

### Indexing 1D array 

In [36]:
arr = np.arange(1,25,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [37]:
# From this grab 15, 17 ( ie 8th, 9th element) 
# This is just similar to list indexing 

In [38]:
arr[7:9]

array([15, 17])

In [39]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

### Reversing the 1 D Array with indexing

In [40]:
## Reversing the array similar to list reversal
arr[::-1]

array([23, 21, 19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

### Indexing 2D arrays

In [41]:
# in two dimensional arrays
arr = np.arange(1, 26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Getting Row/Rows in 2D array

In [42]:
#get row 3
arr[3,]

array([16, 17, 18, 19, 20])

In [43]:
# get rows 2, 3, 4
arr[2:5,]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Getting a chunk of a row

In [44]:
# get 2,3,4 as a single row
arr[0:1 ,1:4 ] #First grab row1 alone

array([[2, 3, 4]])

### Getting Column/Columns

In [45]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [46]:
# Get column 2nd
x = arr[0:5 ,1:2]
x

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [47]:
# Making this to a list of list 
# Futher this can be made to a flat list with list comprehensions or functions
x.tolist()

[[2], [7], [12], [17], [22]]

In [ ]:
# Get two columns, 2,3 ,4
arr[0:5,1:3]

### Numpy Functions -- Work in progress